apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-limits-webhook
  namespace: webhooks
  labels:
    app: validation-limits-webhook
spec:
  selector:
    matchLabels:
      app: validation-limits-webhook
  template:
    metadata:
      labels:
        app: validation-limits-webhook

    spec:
      containers:
      - image: pedroramosolivera/validation-limits-webhook:0.0.1

        name: validation-limits-webhook
        ports:

          - containerPort: 8443
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/certs/webhook

          name: tls
          readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: validate-webhook-cert
