apiVersion: v1
kind: Service
metadata:
  name: validation-limits-webhook
  namespace: webhooks
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: validation-limits-webhook
