apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - name: echo
      port: 8080
      targetPort: 8080
      nodePort: 30040
      protocol: TCP