apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: validate-webhook-cert
  namespace : webhooks
spec:
  commonName: 'validation-limits-webhook.webhooks.svc'
  dnsNames:
    - 'validation-limits-webhook.webhooks.svc'

  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: ca-issuer
  secretName: validate-webhook-cert
